### ISSUE TITLE
Ores

### ISSUE THREAD

**Issue by DoughnutDev** [CelesTek-Team/HexCraft#1]
Ores are not spawning and do you plan on adding cfg so we can tweak it?

**Comment by CelesTek-Team** [comment]
We used Minecraft's methods for ore spawning, so there shouldn't be any issues with it.

Can you give us the list of mods you're running HEXCraft alongside with?

As an extra note, we deliberately made the ore spawns much more rare than they were in XyCraft, here's some info on our [wiki](http://wiki.celestek.xyz/index.php?title=Hexorium_Ore).

As for configurations, we will be implementing that in the upcoming versions, stay tuned.

**Comment by DoughnutDev** [comment]
Do they only spawn in the overworld?

**Comment by CelesTek-Team** [comment]
No, Hexorium Ore spawns both in The Nether and in The Overworld.

**From the wiki:**

> Hexorium Ore spawns naturally in the Overworld and can easily be identified by its characteristic glow-in-dark effect. For the counterpart that spawns in the Nether, visit the Hexorium Nether Ore page.

**Related pages:**
- [Hexorium Ore](http://wiki.celestek.xyz/index.php?title=Hexorium_Ore)
- [Hexorium Nether Ore](http://wiki.celestek.xyz/index.php?title=Hexorium_Nether_Ore)

Please let us know if that answers your questions and resolves the problems you're having, so we know when we can close the issue.

**Comment by CelesTek-Team** [comment]
All questions have been answered.

**Comment by CelesTek-Team** [comment]
Version 0.6.0 now features ore gen config.
