### ISSUE TITLE
[information] -nondescript requirements

### ISSUE THREAD

**Issue by Brian151** [CelesTek-Team/HexCraft#10]
Was going to try this mod out with a friend, but we weren't sure exactly which version of forge to use. Also had issues finding the EXACT version of the required libraries because the links direct to their project pages and not the specific version. I couldn't even find the exact version of Colored Lights core.

Better links and version numbers, please.

The mod didn't get tried-out because it's hard-enough as-is to get my friend to install forge. Trying to be certain we were grabbing all the right dependencies made both of us rage-quit that entire operation.

**Comment by CelesTek-Team** [comment]
The GitHub project is designed more/less just for the source code. The dependencies like Colored Lights are required only to build the project, not to run the mod. All info that you couldn't find is easily available both in our Minecraft Forum thread (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2433456-wip-forge-1-7-10-hexcraft-beta-0-8-0-energy-node) and Curse mod page (http://minecraft.curseforge.com/projects/hexcraft). In addition, Minecraft itself should tell you which Forge version is required when you attempt to launch it with a too old version.

**Comment by CelesTek-Team** [comment]
Regardless, we will update the mod today with an updated readme file.

**Comment by Brian151** [comment]
Yes, that'd be nice. Trial and Error is not a fun way to identify a compatibility problem, especially with large mod APIs like Forge. 

Thanks, I'll close this now...unless you have anything further to add?.

**Comment by CelesTek-Team** [comment]
The readme file has been updated with the information you requested.
