### ISSUE TITLE
latest version launcher crash

### ISSUE THREAD

**Issue by wakkytabbaky** [CelesTek-Team/HexCraft#12]
with the latest version it crashes when loading up, pretty sure its micro blocks that is causing it as the 0.8.2 version is working fine with it

http://pastebin.com/6YfNPgZG

ForgeMultipart-1.7.10-1.1.0.314-universal is the version of multi-part also

Chisel-1.7.10-1.5.7 version

might not be the reason but server is also running cauldron-1.7.10-1.1236.05.212-server

EDIT: seeing as the multipart version is a few versions ahead that might just be the causing of the crash :P

**Comment by CelesTek-Team** [comment]
Indeed that is causing the crash. In fact, all mods are probably partially to blame. All of your mods are waaaaaay behind. Please update your mods. :)

CodeChickenCore: 1.0.4.29 vs 1.0.7.47
ForgeMultipart: 1.1.0.314 vs 1.2.0.345
Chisel: 1.5.7 vs 2.9.4.10
