### ISSUE TITLE
Hexorium-Glass Package is uncraftable

### ISSUE THREAD

**Issue by Z4ckTheGreat** [CelesTek-Team/HexCraft#13]
Recipe does not show up in NEI and isn't craftable. I already double checked the wiki to ensure I had the correct configuration of items to craft it. I tested this on a fresh setup as well with no mods but NEI and ChickenCore.

My Forge version is 10.13.4.1558, and I checked that the mod is up-to-date.

If you need any more info let me know!

**Comment by CelesTek-Team** [comment]
That is weird, can you please send us a screenshot of the crafting grid?

**Comment by Z4ckTheGreat** [comment]
![2016-03-28_20 54 17](https://cloud.githubusercontent.com/assets/17578660/14095580/6d3b54cc-f527-11e5-8d46-70285623a4f1.png)

**Comment by CelesTek-Team** [comment]
That is very weird, considering we are unable to recreate the bug. It looks almost as if something is screwing up the ore dictionary... It could potentially be some weird bug with Java 7/Java 8. Which of these are you running?

**Comment by Z4ckTheGreat** [comment]
I am running it in Java 8 (1.8.0_60).

**Comment by CelesTek-Team** [comment]
Would you by any chance be able to try with Java 7? A variety of mods are still having some issues with 8, so it's worth checking if it's related.

**Comment by Z4ckTheGreat** [comment]
I loaded the mod with Java 7 (1.7.0_80) instead of Java 8 and still the problem persists. (tested on a fresh install with no other mods)

![stillnotworking](https://cloud.githubusercontent.com/assets/17578660/14301020/f8a9d118-fb59-11e5-9e25-a8c0813439b8.png)

If it is any constellation, I am using the MultiMC launcher because it is easier for me to use than using the regular launcher. I doubt this would cause an issue, but I'd figure I mention it anyways.

**Comment by CelesTek-Team** [comment]
It really shouldn't, we use MultiMC as well. Would you be willing to export the instance and send it to us? You can do it to our email which you can find in all of our source files as a comment near the top.

**Comment by Z4ckTheGreat** [comment]
I will! I'm uploading it now and sending it to your email as soon as the upload is finished (my internet is slow).

**Comment by CelesTek-Team** [comment]
Thank you! 

It ends up it is a really stupid reason behind the issue, and it is our fault. We will be updating the mod ASAP to fix it. 

Essentially, the mod EnderIO adds oredict entry for Minecraft's Glass block. We thought Forge did this automatically, similar to ingots and ores, however, it seems that EnderIO is responsible for that entry. A quick fix would be to add EnderIO to your modpack, but I assume this is not something you want to be forced to do, so we will be updating the mod. 

Thank you for letting us know!

**Comment by Z4ckTheGreat** [comment]
No problem! Ah, that is kind of silly. I used to have EnderIO in my modpacks but I stopped using it, I can't remember why.

Anyways glad to see it being fixed, I'll download the new version when it becomes available and make sure it works. Since it is just an oredict issue, I'll close this issue. Thanks so much for all your help.

**Comment by CelesTek-Team** [comment]
We will keep this open until we fix it, because it is still our fault for testing with additional mods loaded and not relying on vanilla MC only.

**Comment by kopilo** [comment]
Hi,
I came across this exact issue using MultiMC: Not sure if it helps but the work around I'm currently using is a custom recipe mod and re-adding the recipe(s) in, (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286235-custom-recipes-make-customize-and-remove-crafting).

**Comment by kopilo** [comment]
Given that the issue seems to be with the recipe I decided to go ahead and try to fix the issue myself.
I have found that adding [the following](https://gist.github.com/kopilo/73663edbebfbb537fe4c0fb80fbf7601) at around line 2814 in HexRecipes.java solved the issue. 
I haven't tested with enderio yet, but as this is adding recipes and not removing them I don't anticipate it being a problem.

**Comment by CelesTek-Team** [comment]
Yes, that is what should fix it. We haven't released any updates yet because of a project at college taking up all of the main coder's time, so we planned to release it next week. Sorry for having to wait that long. xD

**Comment by CelesTek-Team** [comment]
This has now been fixed in version 0.8.5! :)
