### ISSUE TITLE
Ticking Screen Crash on MP login

### ISSUE THREAD

**Issue by Deckee** [CelesTek-Team/HexCraft#14]
Forge: 10.13.4.1614-1.7.10
Jre: jre1.8.0.92 and jre1.7.0.80
Light Loader 1.7.10-4
[latest.txt](https://github.com/CelesTek-Team/HexCraft/files/333907/latest.txt)
[fml-client-3.txt](https://github.com/CelesTek-Team/HexCraft/files/333909/fml-client-3.txt)

**Comment by Deckee** [comment]
It seems to be related to  @wasliebob 's FMPI

**Comment by CelesTek-Team** [comment]
There doesn't seem to be anything here that points to HEXCraft... But there seems to be errors from IC2 when connecting to the server instead.

`[18:57:24] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel FML
java.lang.RuntimeException: Can't insert handler in [DefaultChannelPipeline$TailHandler#0].
    at ic2.core.network.RpcHandler.onConnect(RpcHandler.java:104) ~[RpcHandler.class:?]`

Regardless, can you please try to remove just HEXCraft and try again?

**Comment by Deckee** [comment]
it was @wasliebob 's FMPI trying to add all of hex crafts blocks into Fmp, causing it to crash.  I installed
Fmp +   FMPI + hexcraft and it crashed, A fix is to ban hexcraft from fmpi in the .cfg
http://paste.ee/p/dHIpS
edit, liteloader + voxel map are not effecting the crash
log with out liteloader and voxelmap http://paste.ee/p/t2p4z

**Comment by ghost** [comment]
It crashes even with only ForgeMultipart, WR-CBE (and requiried coremods), HexCraft installed. And I never used FMPI.

[crash-2018-03-19_16.51.53-client.txt](https://github.com/CelesTek-Team/HexCraft/files/1825478/crash-2018-03-19_16.51.53-client.txt)

**Comment by CelesTek-Team** [comment]
Literally all mods other than HEXCraft that you are trying to use are outdated, especially the ForgeMultipart (current is 1.2, you are using 1.1). Please update and try again. The error is caused because HEXCraft is trying to call methods that don't yet exist in your version of ForgeMultipart.

**Comment by ghost** [comment]
It was suprise to me that ForgeMultipart was so outdated, because I downloaded latest WR-CBE 2-3 months ago which automatically downloaded FMP, and it was that old version. After updating it manually it worked, thanks.

**Comment by CelesTek-Team** [comment]
Glad to hear that it is now sorted out!
