### ISSUE TITLE
A few things after playing around a bit

### ISSUE THREAD

**Issue by Fortist** [CelesTek-Team/HexCraft#15]
1) The hitbox/block box of a pylon base and pylon is misleading and I tend to hit the block behind if looking from the side.
2) The teleport pads are really counter intuitive if you're trying to teleport far enough away. You have to connect two with a pipe/tube? why not just have them connect with the linker and power them?
3) There is nothing special to do with Hex power. Granted, with a heavily modded pack.
I think Im just gonna use this for Deco.

**Comment by CelesTek-Team** [comment]
1) We are aware of this. It was done because of the ray tracing algorithm used when connecting the pylons. It may or may not be changed.
2) Not everything has to be simple in life.
3) We suggest you look into the Energy Node and what you can do with it.
