### ISSUE TITLE
Are there any plans to move the mod to 1.1x？

### ISSUE THREAD

**Issue by forestbat** [CelesTek-Team/HexCraft#17]
As the topic。

**Comment by ghost** [comment]
They said that they couldnt recreate glowing textures in newer mc versions. BUT I guess they could use Emmisive textures feature from optifine!

**Comment by CelesTek-Team** [comment]
This mod will not rely on mods like Optifine, as it was always breaking Minecraft in unexpected ways. There might be an update if someone can make the glow work properly and exactly how it should, but it is highly unlikely anyone would manage.

Some might say that many other mods already have similar glow like our mod, but they do not. Not a single other mod uses alpha transparency on the textures to create the highly detailed cutouts on the textures like we do.

**Comment by CelesTek-Team** [comment]
We have actually started the porting process some time ago. Everything has to be made completely from scratch (other than stuff like textures ofc), so it is a long process: https://github.com/CelesTek-Team/HEXCraft-for-1.12.2
