### ISSUE TITLE
Hexorium-Glass Package has no recipe

### ISSUE THREAD

**Issue by NelkGames** [CelesTek-Team/HexCraft#18]
I'm playing with a pack of mods I made, but the Hexcraft mod did not create the Hexorium-Glass Package recipe.
I'm playing version 1.7.10, and the mod version is the latest: 0.11.0

**Comment by CelesTek-Team** [comment]
That is incredibly weird. Can you please do the following things:
1) Install Not Enough Items (if you don't have it already) and check if the recipe is present there
2) If not, post the full list of mods that you have

**Comment by NelkGames** [comment]
I'm using Not Enough Items.

and here is the list of mods I'm playing:  
  [1.7.10]MoVillages-1.4.2
  [1.7.10]Treecapitator-universal-2.0.4
  ABO-MC1.7.10-BC7.1release4.0.9
  Aroma1997Core-1.7.10-1.0.2.16
  AromaBackup-1.7.10-0.1.0.0
  BetterFps-1.0.1
  buildcraft-7.1.23
  buildcraft-compat-7.1.7
  ChickenChunks-1.7.10-1.3.4.19-universal
  CodeChickenCore-1.7.10-1.0.7.47-universal
  DynamicSurroundings-1.7.10-1.0.6.3
  EnderStorage-1.7.10-1.4.7.38-universal
  forestry_1.7.10-4.2.16.64
  FpsReducer-1.7.10-1.10.1
  gadomancy-1.7.10-1.0.7.3
  HEXCraft-1.7.10-0.11.0
  IC2NuclearControl-2.4.3a
  industrialcraft-2-2.2.827-experimental
  InventoryTweaks-1.59-dev-152
  ironchest-1.7.10-6.0.62.742-universal
  logisticspipes-0.9.3.132
  magicbees-1.7.10-2.4.4
  neiaddons-1.12.15.41-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.2
  NotEnoughItems-1.7.10-1.0.5.120-universal
  OptiFine_1.7.10_HD_U_E7
  ProjectE-1.7.10-PE1.10.1
  ProjectRed-1.7.10-4.7.0pre12.95-Base
  ProjectRed-1.7.10-4.7.0pre12.95-Compat
  ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
  ProjectRed-1.7.10-4.7.0pre12.95-Integration
  ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
  ProjectRed-1.7.10-4.7.0pre12.95-World
  Railcraft_1.7.10-9.12.2.1
  Thaumcraft-1.7.10-4.2.3.5
  thaumcraftneiplugin-1.7.10-1.7a
  ThaumicExploration-1.7.10-1.1-53
  Traincraft-4.4.0_016
  WR-CBE-1.7.10-1.4.1.11-universal
  Xaeros_Minimap_1.15.3_Forge_1.7.10

**Comment by Thorinair** [comment]
This should be fixed on the new upcoming version of the mod (should release in a few days or sooner). The reason was that some mods (in this case EnderIO) add additional Ore Dictionary entries, in this case for glass, and I was relying on them like a dummy.
