### ISSUE TITLE
Random crash while placing pilons on a base.

### ISSUE THREAD

**Issue by LuxusDarkangel** [CelesTek-Team/HexCraft#2]
Crash report: http://pastebin.com/2aXEZMrH
Forge version: 10.13.4.1481
HEXCraft version: 0.5.1

Note: Yeah, i know it's a problem with railcraft, but doesn't look like something on their end.
EDIT: It occurs also when i place just the base.

**Comment by CelesTek-Team** [comment]
This is a known issue with Railcraft which affects a lot of different mods.

Simply disable the heat feature.

The issue is on their side, as Railcraft is replacing our tile entities with their own. There is nothing we can do here.

**Comment by LuxusDarkangel** [comment]
Yep, disabling residual heat solves the problem. Sorry for blaming your mod and thanx for the support :)

**Comment by CelesTek-Team** [comment]
No worries.

Don't shy away from reporting any future bugs you come across, we appreciate it :)
