### ISSUE TITLE
Crash linking two Personal Teleportation Pad.

### ISSUE THREAD

**Issue by LuxusDarkangel** [CelesTek-Team/HexCraft#3]
Crash report: http://pastebin.com/RAPf5C4L
Forge version: 10.13.4.1481
HEXCraft version: 0.5.1

Other notes: Tested on SSP.

**Comment by CelesTek-Team** [comment]
Could you post steps to reproduce the crash?

What was the distance between the pads, how did you connect them? Direct connection with cables or did you use pylons with cables?

**Comment by LuxusDarkangel** [comment]
Steps: Place two teleports (the distance between the pads were 8 blocks), charge them to 200% (don't know if this is truly neccesary), try to link them using Hexorium Manipulator WHITOUT connecting them with cables.
Crashes randomly under this circumstances (not always, sometimes it displays the "Linking failed. Teleport unreachable" message)

Additional notes: Everytime it crashes, when i load again the world it shows the linking failed message, and the teleporter has rotated, maybe it's trying to link them and rotate it at the same time?

**Comment by CelesTek-Team** [comment]
Thank you for sharing the details! We will be fixing it during next week and push it as soon as the new update is ready.

**Comment by LuxusDarkangel** [comment]
No problem, it's always a pleasure help newly released mods to solve its problems and grow.

**Comment by CelesTek-Team** [comment]
Fixed in 0.6.0
