### ISSUE TITLE
[Enhancement] Different Creative Tabs.

### ISSUE THREAD

**Issue by LuxusDarkangel** [CelesTek-Team/HexCraft#4]
At the moment the Hexcraft creative tab is very messy and it's hard to search for something, you have a cable, some different blocks, another cable, one pilon, some other blocks, another cable, etc. Adding more creative tabs for each category (as it's organized in the code) would be very nice.

**Comment by CelesTek-Team** [comment]
Sounds like a good idea. Added to the list of things to change/implement.

**Comment by CelesTek-Team** [comment]
Added more tabs in 0.6.0
