### ISSUE TITLE
[Feature request] Xycraft multi tank and fabricator.

### ISSUE THREAD

**Issue by LuxusDarkangel** [CelesTek-Team/HexCraft#7]
Xycraft multi tank and fabricator were some of the most useful features on the xycraft pre-release for mc 1.4.7, would be great bring them back.

**Comment by Brian151** [comment]
IDK what CelesTek have planned, but I did talk with one of them about this mod. One thing mentioned is they're actually trying to be somewhat 'original', as opposed to the blatant copycat clones out there. Which also may prevent Soaryn from taking action. (even though he shouldn't be able to in the first place) Honestly, I just want the decorative blocks!  agree those tanks were useful. I've heard they also caused horrible server lag and crashes, though... iirc, Mindcrack had an issue with that when they did the FTB pack

**Comment by CelesTek-Team** [comment]
Actually, we are already working on a tank, but it probably won't be there for the next update. However, it will be there very soon! By the way, tanks can be made very efficiently without a fear of corrupting a world, causing lag or crashes. That is what we strive for.
As for the fabricators, that might have to wait as it is not on our todo list yet.

**Comment by LuxusDarkangel** [comment]
I think i can close this...
