### ISSUE TITLE
Odd Pylon Rendering

### ISSUE THREAD

**Issue by Dragonzrkool** [CelesTek-Team/HexCraft#9]
Hello, I'm a little unsure of where to ask this or if this has been addressed before so sorry if it has or I need to be asking elsewhere.

I want to start off by saying I've only recently come across this mod but I absolutely adore it. There is only one thing offputting me from it for now. I'm having an issue with how the Energy Pylon renders. Using version 0.8.0 the energy pylon renders as if it were a broken texture cable:

In Inventory: http://imgur.com/CwjvT60
Placed on Ground: http://imgur.com/FdlXbZT
Pylons attempting to link as a cable: http://imgur.com/0K6gGlK

Strangely enough, the block itself functions perfectly fine. I can install a monolith and link the two together with the manipulator, but neither the monolith or beam will be rendered.

Initially I thought that it was a conflict from some other mod (I had a lot), so I went to the extent of completely wiping my MC data and installing fresh - complete with the latest version of forge. However the problem still persists. I asked a friend to attempt to use the mod as well, and he received  the same issue. In my final bit of experimentation, I used version 0.7.0 and did NOT get the rendering issue - the pylon, monolith, and beam were all working perfectly fine.

I apologize that I cannot offer a crash report or anything, as the mod works perfectly fine without any crashing aside from this odd rendering issue. If there's any more information you require that I have not provided please let me know.

Thank you,
Dragonz

**Comment by CelesTek-Team** [comment]
Ouch, we know exactly why this is happening and we will fix it as soon as possible. Probably even today.

**Comment by Dragonzrkool** [comment]
Ah alright! Thanks for the fast response, and looking forward to it.

**Comment by CelesTek-Team** [comment]
The update is out! Thank you for finding this issue so we could correct it as quickly as possible.
